blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, activates

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name="blog_create"),
    path('', BlogListView.as_view(), name="blog_list"),
    path('blog/<int:pk>', BlogDetailView.as_view(), name="blog_detail"),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name="blog_update"),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name="blog_delete"),
    path('activate/<int:pk>', activates, name="blog_activate"),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from catalog.views import fobidden_view403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace="catalog")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('users/', include('users.urls', namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = fobidden_view403

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=250, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)
    content = models.TextField(verbose_name='Содержимое')
    photo = models.ImageField(null=True, blank=True, verbose_name='Превью', upload_to='blog/')
    created_at = models.DateField(auto_now=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Статус публикации')
    count_views = models.IntegerField(verbose_name='Количество просмотров', default=0)

    def __str__(self):
        return f"{self.title} {self.created_at}"

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'slug', 'photo',)
    success_url = reverse_lazy('catalog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()
        return self.object


class BlogUpdateView(PermissionRequiredMixin, UpdateView):
    model = Blog
    fields = ('title', 'content', 'slug', 'photo',)
    # success_url = reverse_lazy('catalog:blog_detail')
    permission_required = 'blog.change_blog'

    def get_success_url(self):
        return reverse('catalog:blog_detail')


class BlogDeleteView(PermissionRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:blog_list')
    permission_required = 'blog.delete_blog'


def activates(request, pk):
    blogs_item = get_object_or_404(Blog, pk=pk)
    if blogs_item.is_published:
        blogs_item.is_published = False
    else:
        blogs_item.is_published = True
    blogs_item.save()
    return redirect(reverse('blog:blog_list'))

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить блог "{{ object.title }}"</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'blog:blog_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>

            </div>
        </div>
    </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load media_tags %}
{% block content %}
{% include 'catalog/includes/inc_menu.html' %}
<div class="container justify-content-center">
    <div class="row text-center">

        <div class="col-12 mh-45">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
<!--                    <h4 class="my-0 font-weight-normal">{{ product.category.name }}</h4>-->
                </div>
                <div class="card-body">

                        <h2 class="card-title pricing-card-title">{{ object.title }}</h2>
                        <img src="{{ object.photo|mymedia }}" alt="{{ object.title }}">
                        <ul class="list-unstyled mt-3 mb-4 text-center m-3">
                            <li class="mb-4">{{ object.content }}</li>

                            <li class="text-start">Опубликовано {{ object.is_published }}</li>
                            <li class="text-start">Дата создания {{ object.created_at }}</li>
                        </ul>


                </div>
                <div class="card-footer">
                    <h3>Количество просмотров: {{ object.count_views }}</h3>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>

            </div>
        </div>
    </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}
{% include 'catalog/includes/inc_menu.html' with objects=objects %}

<div class="container">
    <div class="row text-center">

        <a href="{% url 'blog:blog_create' %}" type="button"
           class="mb-3 form-control btn btn-lg btn-primary">Создать</a>

        {% for object in object_list %}
        <div class="col-4 mh-45">

            <div class="card mb-4 box-shadow">

                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.category.name }}</h4>
                </div>
                <div class="card-body">

                    <h3 class="card-title pricing-card-title">{{ object.title | truncatechars:'23' }}</h3>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li class="mb-2">{{ object.content | truncatechars:'100' }}</li>


                    </ul>

                    <a href="{% url 'blog:blog_detail' object.pk %}" type="button"
                       class="mb-3 form-control btn btn-lg btn-success">Просмотр</a>
                    {% if perms.blog.change_blog %}
                    <a href="{% url 'blog:blog_update' object.pk %}" type="button"
                       class="mb-3 form-control btn btn-lg btn-warning">Редактировать</a>
                    {% endif %}
                    {% if perms.blog.delete_blog %}
                    <a href="{% url 'blog:blog_delete' object.pk %}" type="button"
                       class="mb-3 form-control btn btn-lg btn-danger">Удалить</a>
                    {% endif %}
                    {% if perms.blog.change_blog %}
                    <a href="{% url 'blog:blog_activate' object.pk %}" type="button"
                       class="mb-3 form-control btn btn-lg btn-info">

                        {% if object.is_published %}
                        Деактивировать
                        {% else %}
                        Активировать
                        {% endif %}
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}