blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, activates

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name="blog_create"),
    path('', BlogListView.as_view(), name="blog_list"),
    path('blog/<int:pk>', BlogDetailView.as_view(), name="blog_detail"),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name="blog_update"),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name="blog_delete"),
    path('activate/<int:pk>', activates, name="blog_activate"),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from catalog.views import fobidden_view403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace="catalog")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('users/', include('users.urls', namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = fobidden_view403

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users import views
from users.apps import UsersConfig
from users.views import activate, password_reset

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),

    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
         activate, name='activate'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('register_info/', views.TemplateView.as_view(template_name='users/register_info.html'), name='register_info'),
    path('register_done/', views.TemplateView.as_view(template_name='users/register_done.html'), name='register_done'),
    path('register_error/', views.TemplateView.as_view(template_name='users/register_error.html'),
         name='register_error'),
    path('password_reset/', password_reset, name='password_reset_form'),
    path('password_reset/done/', views.TemplateView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта')
    avatar = models.ImageField(upload_to='users/', default='users/pixlr-bg-result_9.png', **NULLABLE,
                               verbose_name='Аватар')
    phone = models.CharField(max_length=35, **NULLABLE, verbose_name='Телефон')
    country = models.CharField(max_length=100, **NULLABLE, verbose_name='Страна')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User

class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field, forms.BooleanField):
                field.widget.attrs.update({'class': 'form-check-input'})



class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'phone', 'avatar']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
import string

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView

from users import forms
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User

from django.contrib.auth.views import FormView
from django.core.mail import send_mail, EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_str

from users.token import account_activation_token


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:register_info')

    def form_valid(self, form):
        # Сохранение пользователя
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # Получение текущего сайта
        current_site = get_current_site(self.request)

        # Подготовка данных для отправки электронного письма

        mail_subject = 'Теперь вы зарегистрированы на нашем сервисе! Подтвердите свой электронный адрес.'
        message = render_to_string('users/acc_active_email.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': account_activation_token.make_token(user),
        })
        to_email = form.cleaned_data.get('email')
        email = EmailMessage(
            mail_subject, message, to=[to_email]
        )
        email.send()
        return super().form_valid(form)

    def form_invalid(self, form):
        form = UserRegisterForm
        return super().form_invalid(form)


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True

        user.save()

        group = Group.objects.get(name='Право на изменение')
        user.groups.add(group)
        return redirect(reverse('users:register_done'))
    else:
        return redirect(reverse('users:register_error'))


def password_reset(request):
    if request.method == 'POST':
        email = request.POST['email']
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            return render(request, 'users/password_reset_form.html',
                          {'error_message': 'Пользователь с таким email не найден'})
        new_password = ''.join([random.choice(string.ascii_letters + string.digits) for _ in range(10)])
        send_mail(
            subject='Вы сменили пароль',
            message=f'ваш новый пароль: {new_password}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
        )

        user.set_password(new_password)
        user.save()

        return redirect(reverse('users:password_reset_done'))
    return render(request, 'users/password_reset_form.html')

users/templates/users/acc_active_email.html
{% autoescape off %}
Hi ,
Пожалуйста, нажмите на ссылку, чтобы подтвердить свою регистрацию,
http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="col-12">
            <div class="row g-3 align-items-center">
                <div class="col-3">
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0">
                    <div class="card mb-3 mt-4 box-shadow">
                        <div class="card-header text-center mb-3">
                            <h4 class="my-0 font-weight-normal mb-3 mt-2">Вход в систему</h4>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <p>
                                <div class="mb-3 row">
                                    <label for="id_username" class="col-sm-2 col-form-label">Email address:</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="254" required="" aria-invalid="true" id="id_username">
                                    </div>
                                </div>
                            </p>
                            <p>
                                <div class="mb-3 row">
                                    <label for="id_password" class="col-sm-2 col-form-label">Password:</label>
                                    <div class="col-sm-10">
                                        <input type="password" class="form-control" name="password" autocomplete="current-password" required="" aria-invalid="true" id="id_password">
                                    </div>
                                </div>
                            </p>
                            <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                                <button class="btn btn-success me-md-2" type="submit">Войти</button>
                                <a href="{% url 'users:password_reset_form' %}" class="btn btn-danger" type="button">Восстановить пароль</a>
                            </div>
                             <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-2">
                                 <p><a href="{% url 'users:register' %}" class="link-secondary">Зарегистрироваться</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-3">
            </div>
        </div>
    </form>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'catalog/base.html' %}

{% block content %}
    {% if validlink %}
        <p>Пожалуйста, введите (и подтвердите) свой пароль</p>
        <form action="" method="post">
            {% csrf_token %}
            <table>
                
            </table>

        </form>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="check-circle-fill" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </symbol>
        <symbol id="info-fill" viewBox="0 0 16 16">
            <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
        </symbol>
        <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </symbol>
    </svg>

    <div class="alert alert-primary d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Info:">
            <use xlink:href="#info-fill"/>
        </svg>
        <div>
            <p class="h2">
                <em>Мы отправили вам по электронной почте инструкции по установке пароля.
    Если они не получены в течении нескольких минут, то проверте папку со спамом</em>
            </p>
        </div>
    </div>
    <div class="d-grid gap-2">
        <a class="btn btn-outline-primary" type="button" href="{% url 'users:login' %}">Вернуться на страницу входа</a>
    </div>
{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="col-12">
            <div class="row g-3 align-items-center">
                <div class="col-3">
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0">
                    <div class="card mb-3 mt-4 box-shadow">
                        <div class="card-header text-center mb-3">
                            <h4 class="my-0 font-weight-normal mb-3 mt-2">Востановление пароля</h4>
                        </div>
                        <div class="card-body">
                            <h2>Введите свой адрес электронной почты</h2>
                            {% csrf_token %}
                            <p>
                                <div class="mb-3 row">
                                    <label for="email" class="col-sm-2 col-form-label">Email address:</label>
                                    <div class="col-sm-10">

                                        <input type="text" class="form-control" name="email" autofocus="" autocapitalize="none" autocomplete="username" maxlength="254" required="" aria-invalid="true" id="email">
                                        <ul>
                                            {% if error_message %}
                                            <li class="mb">{{ error_message }}</li>
                                            {% endif %}
                                        </ul>

                                    </div>
                                </div>
                            </p>
                            <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                                <button class="btn btn-outline-success me-md-2" type="submit">Восстановить пароль</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-3">
            </div>
        </div>
     </form>
{% endblock %}

users/templates/users/password_reset_invalid.html
{% extends 'catalog/base.html'%}

{% block content %}
   <p>Произошла ошибка при восстановлении пароля. Пожалуйста, проверьте правильность введенного адреса электронной почты и повторите попытку.</p>
{% endblock %}

users/templates/users/password_resset_email.html
Здравствуйте,

Вы получили это письмо, потому что запросили восстановление пароля для вашей учетной записи.

Чтобы восстановить пароль, перейдите по следующей ссылке:
<a href="{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}">Восстановить пароль</a>

Если вы не запрашивали восстановление пароля, проигнорируйте это письмо.

С уважением,
Ваша команда сайта

users/templates/users/register.html
{% extends 'catalog/base.html'%}

{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">Регистрация</h2>
                </div>
                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>

                </div>
                <div class="card-footer"></div>
            </div>
        </div>

    </form>
</div>

{% endblock %}

users/templates/users/register_done.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="check-circle-fill" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </symbol>
        <symbol id="info-fill" viewBox="0 0 16 16">
            <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
        </symbol>
        <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </symbol>
    </svg>

    <div class="alert alert-success d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Success:">
            <use xlink:href="#check-circle-fill"/>
        </svg>
        <div>
            <p class="h2">
                <em>Ваша учетная запись активирована, теперь вы можете перейти в главное меню</em>
            </p>
        </div>
    </div>
    <div class="d-grid gap-2">
        <a class="btn btn-outline-primary" type="button" href="{% url 'users:login' %}">Вернуться на страницу входа</a>
    </div>
    {% endblock %}

users/templates/users/register_error.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="check-circle-fill" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </symbol>
        <symbol id="info-fill" viewBox="0 0 16 16">
            <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
        </symbol>
        <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </symbol>
    </svg>

    <div class="alert alert-danger d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:">
            <use xlink:href="#exclamation-triangle-fill"/>
        </svg>
        <div>
            <p class="h2">
                <em>Ваша ссылка повреждена</em>
            </p>
        </div>
    </div>
    <div class="d-grid gap-2">
        <a class="btn btn-outline-primary" type="button" href="{% url 'users:login' %}">Вернуться на страницу входа</a>
    </div>
    {% endblock %}

users/templates/users/register_info.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="check-circle-fill" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </symbol>
        <symbol id="info-fill" viewBox="0 0 16 16">
            <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
        </symbol>
        <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </symbol>
    </svg>

    <div class="alert alert-primary d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Info:">
            <use xlink:href="#info-fill"/>
        </svg>
        <div>
            <p class="h2">
                <em>На вашу почту было отправлено сообщение с подтверждением регистрации, для подтверждения учетной записи перейдите по ссылке в сообщении</em>
            </p>
        </div>
    </div>
    <div class="d-grid gap-2">
        <a class="btn btn-outline-primary" type="button" href="{% url 'users:login' %}">Вернуться на страницу входа</a>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html'%}

{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">Профиль</h2>
                </div>
                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>

                </div>
                <div class="card-footer"></div>
            </div>
        </div>

    </form>
</div>

{% endblock %}