blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, activates

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name="blog_create"),
    path('', BlogListView.as_view(), name="blog_list"),
    path('blog/<int:pk>', BlogDetailView.as_view(), name="blog_detail"),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name="blog_update"),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name="blog_delete"),
    path('activate/<int:pk>', activates, name="blog_activate"),

]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from catalog.apps import MainConfig
from catalog.views import ProductListView, ProductDatailView, ContactView, ProductCreateView, ProductDeleteView, \
    CategoryListView, ProductUpdateView

app_name = MainConfig.name

urlpatterns = [

    path('', ProductListView.as_view(), name="index"),
    path('contacts/', ContactView.as_view(), name="contacts"),
    path('category/', CategoryListView.as_view(), name="category"),
    path('product/<int:pk>/', cache_page(60)(ProductDatailView.as_view()), name="product_detail"),
    path('product/create/', ProductCreateView.as_view(), name="product_create"),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name="product_update"),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name="product_delete"),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from catalog.views import fobidden_view403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace="catalog")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('users/', include('users.urls', namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = fobidden_view403

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users import views
from users.apps import UsersConfig
from users.views import activate, password_reset

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),

    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
         activate, name='activate'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('register_info/', views.TemplateView.as_view(template_name='users/register_info.html'), name='register_info'),
    path('register_done/', views.TemplateView.as_view(template_name='users/register_done.html'), name='register_done'),
    path('register_error/', views.TemplateView.as_view(template_name='users/register_error.html'),
         name='register_error'),
    path('password_reset/', password_reset, name='password_reset_form'),
    path('password_reset/done/', views.TemplateView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
]

catalog/models.py
from django.db import models
from django.utils import timezone

from users.models import User


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.name} ({self.description})'

    class Meta:
        verbose_name = 'катекория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    PUBLISHED = 'Опубликовано'
    UNPUBLISHED = 'Не опубликовано'
    STATUS_CHOICES = [(PUBLISHED, 'published'), (UNPUBLISHED, 'unpublished')]

    name = models.CharField(max_length=250, verbose_name='Наименование')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')
    photo = models.ImageField(upload_to='catalog/', null=True, blank=True, verbose_name='Изоброжение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена за покупку')
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateField(auto_now=True, verbose_name='Дата изменения')
    is_published = models.CharField(choices=STATUS_CHOICES, max_length=20, default=UNPUBLISHED, verbose_name='Статус')

    users = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Пользователь', null=True, blank=True,
                              default=None)

    def __str__(self):
        return f'{self.name} {self.description} {self.photo} {self.category} {self.price} {self.created_at} {self.updated_at}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

        permissions = [
            (
                'set_is_published',
                'can publish product',
            ),
            (
                'change_discription',
                'can change product description',
            ),
            (
                'change_category',
                'can change product category',
            )

        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    number_version = models.PositiveIntegerField(verbose_name='Номер версии')
    name_version = models.CharField(max_length=250, verbose_name='Название версии')
    current_version = models.BooleanField(default=True, verbose_name='Текущая версия')

    def __str__(self):
        return f'{self.product} {self.number_version} {self.name_version}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from django.db.models import Q
from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field, forms.BooleanField):
                field.widget.attrs.update({'class': 'form-check-input'})


class ProductFormCatalog(StyleFormMixin, forms.ModelForm):
    words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        # fields = '__all__'
        exclude = ['users']

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        for word in self.words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('Нельзя использовать слово ' + word)
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        for word in self.words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('Нельзя использовать слово ' + word)
        return cleaned_data


class ProductFormAllUser(StyleFormMixin, forms.ModelForm):
    words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published')

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        for word in self.words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('Нельзя использовать слово ' + word)
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

    def clean_current_version(self):
        active_version = []
        version = Version.objects.filter(Q(current_version=True))
        cleaned_data = self.cleaned_data['current_version']
        active_version.append(cleaned_data) if cleaned_data else None
        # if cleaned_data:
        #     active_version.append(cleaned_data)
        if len(active_version) == 1 and version:
            raise forms.ValidationError('Вы можете установить только одну версию в качестве текущей')

        return cleaned_data

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from django.forms import inlineformset_factory

from django.shortcuts import render
from django.urls import reverse, reverse_lazy

from pytils.translit import slugify
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

from .forms import VersionForm, ProductFormCatalog, ProductFormAllUser
from .models import Product, Category, Version
from django.core.exceptions import PermissionDenied

from .services import get_cached_subjects_category


class ProductListView(LoginRequiredMixin, ListView):
    """ Представление для списка продуктов """
    model = Product
    extra_context = {'title': 'Главная'}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.all()

        for product in products:
            versions = Version.objects.filter(product=product)
            active_version = versions.filter(current_version=True).first()
            product.active_version = active_version.name_version if active_version else 'Версия неактивна'

        context['products'] = products

        return context


class ContactView(LoginRequiredMixin, TemplateView):
    """ Представление для отправки сообщения """
    template_name = 'catalog/contact.html'


class ProductDatailView(LoginRequiredMixin, DetailView):
    """ Представление для просмотра продукта """
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    """ Представление для создания продукта """
    model = Product
    form_class = ProductFormCatalog

    success_url = reverse_lazy('catalog:index')

    def form_valid(self, form):
        user_name = form.save()
        user_name.users = self.request.user
        user_name.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    """Представление для редактирования продукта
    наследуется от Product и при наличии прав на редактирование продукта проверяется
    если обычный пользователь и он владелец продукта он может редактировать, если администратор выводит форму
    редактирования
    только по определенным полям"""
    model = Product
    form_class = ProductFormCatalog

    permission_required = ('catalog.change_product', 'catalog.set_is_published', 'catalog.change_discription',
                           'catalog.change_category')

    def get_success_url(self):
        return reverse('catalog:product_update', args=[self.kwargs.get('pk')])

    def get_form_class(self):
        """Получение формы для редактирования продукта"""
        if self.request.user.is_staff and self.request.user.has_perms(
                perm_list=self.permission_required) and not self.request.user.is_superuser:
            return ProductFormAllUser
        elif self.request.user.is_superuser and self.request.user.has_perm('catalog.change_product'):
            return ProductFormCatalog
        else:
            if self.request.user.is_active and self.request.user.has_perm('catalog.change_product'):
                if self.request.user != self.get_object().users and self.request.user.is_active:
                    raise PermissionDenied

                return ProductFormCatalog

    def get_context_data(self, **kwargs):
        # Получение базового контекста с помощью super()

        context_data = super().get_context_data(**kwargs)

        # Создание формсета
        VersionFormSet = inlineformset_factory(Product, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':

            formset = VersionFormSet(self.request.POST, instance=self.object)
        else:
            # Если запрос GET, создаем пустой формсет
            formset = VersionFormSet(instance=self.object)

        # Добавление формсета в контекст
        context_data['formset'] = formset

        return context_data

    def form_valid(self, form):
        # Получение контекста данных
        context_data = self.get_context_data()
        formset = context_data['formset']

        # Сохранение основной формы
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    """Представление для удаления продукта
    наследуется от Product и при наличии прав на удаление продукта вызывается PermissionRequiredMixin"""
    model = Product
    permission_required = 'catalog.delete_product'
    success_url = reverse_lazy('catalog:index')


class CategoryListView(LoginRequiredMixin, ListView):
    """Представление для списка категорий"""
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['subjects'] = get_cached_subjects_category()
        return context_data


def fobidden_view403(request, exception):
    return render(request, 'catalog/access_denied.html', status=403)

catalog/templates/catalog/access_denied.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="check-circle-fill" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </symbol>
        <symbol id="info-fill" viewBox="0 0 16 16">
            <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
        </symbol>
        <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </symbol>
    </svg>

    <div class="alert alert-primary d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Info:">
            <use xlink:href="#info-fill"/>
        </svg>
        <div>
            <p class="h2">
                <em>На просмотр данной страницы вам доступ запрещён</em>
            </p>
        </div>
    </div>
    <div class="d-grid gap-2">
        <a class="btn btn-outline-primary" type="button" href="{% url 'catalog:index' %}">Вернуться на главную</a>
    </div>
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}
{% load media_tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-dark bg-dark p-3 px-md-4 mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Skystore</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar"
                aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar"
             aria-labelledby="offcanvasDarkNavbarLabel">
            <div class="offcanvas-header">
                <div class="dropdown">
                </div>
                <h2 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Меню навигации</h2>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3 mb-3">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {% if user.is_authenticated %}
                                <img src="{{ user.avatar|mymedia }}" alt="" width="32" height="32" class="rounded-circle me-2">
                            {% endif %}
                            <strong>Пользователь</strong>
                        </a>


                        <ul class="dropdown-menu dropdown-menu-dark">
                            {% if user.is_authenticated %}
                                <li>
                                    <form method="post" enctype="multipart/form-data" action="{% url 'users:logout' %}">
                                        {% csrf_token %}
                                        <p class="text-center">{{ user.email }}</p>
                                        <button class="dropdown-item" type="submit">Выйти из профиля</button>
                                    </form>
                                    <a class="dropdown-item" href="{% url 'users:profile' %}">Изменить профиль</a>
                                </li>
                            {% else %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'users:login' %}">Войти в профиль</a>
                                    <a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a>
                                </li>
                            {% endif %}
                        </ul>


                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/category/">Категории</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/">Каталог</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/contacts/">Контакты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog/">Блог</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>


{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить блог "{{ object.title }} {{ object.content}} {{ object.photo }} {{ object.is_published }}"</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'catalog:blog_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>

            </div>
        </div>
    </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load media_tags %}
{% block content%}
{% include 'catalog/includes/inc_menu.html' %}
<div class="container justify-content-center">
    <div class="row text-center">

        <div class="col-12 mh-45">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
<!--                    <h4 class="my-0 font-weight-normal">{{ product.category.name }}</h4>-->
                </div>
                <div class="card-body">

                        <h2 class="card-title pricing-card-title">{{ object.title }}</h2>
                        <img src="{{ object.photo|mymedia }}" alt="{{ object.title }}">
                        <ul class="list-unstyled mt-3 mb-4 text-center m-3">
                            <li class="mb-4">{{ object.content }}</li>

                            <li class="text-start">Опубликовано {{ object.is_published }}</li>
                            <li class="text-start">Дата создания {{ object.created_at }}</li>
                        </ul>


                </div>
                <div class="card-footer">
                    <h3>Количество просмотров: {{ object.count_views }}</h3>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}
{% include 'catalog/includes/inc_menu.html' with objects=objects %}

<div class="container">
    <div class="row text-center">
         <a href="{% url 'catalog:blog_create' %}" type="button" class="mb-3 form-control btn btn-lg btn-primary">Создать</a>
        {% for object in object_list %}
        <div class="col-4 mh-45">

            <div class="card mb-4 box-shadow">

                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.category.name }}</h4>
                </div>
                <div class="card-body" >

                        <h3 class="card-title pricing-card-title">{{ object.title | truncatechars:'40' }}</h3>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li class="mb-2">{{ object.content | truncatechars:'100' }}</li>


                        </ul>
                        <a href="{% url 'catalog:blog_detail' object.pk %}" type="button" class="mb-3 form-control btn btn-lg btn-success">Просмотр</a>
                        <a href="{% url 'catalog:blog_update' object.pk %}" type="button" class="mb-3 form-control btn btn-lg btn-warning">Редактировать</a>
                        <a href="{% url 'catalog:blog_delete' object.pk %}" type="button" class="mb-3 form-control btn btn-lg btn-danger">Удалить</a>
                        <a href="{% url 'catalog:blog_activate' object.pk %}" type="button" class="mb-3 form-control btn btn-lg btn-info">
                        {% if object.is_published %}
                           Деактивировать
                        {% else %}
                           Активировать
                        {% endif %}
                        </a>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% include 'catalog/includes/inc_menu.html' with objects=objects %}

<div class="container">

    <div class="row text-center">
        {% for object in subjects %}
        <div class="col-4 mh-45">
            <div class="card mb-4 box-shadow">
                <div class="card-header">

                </div>
                <div class="card-body">

                    <h3 class="card-title pricing-card-title">{{ object.name | truncatechars:'40' }}</h3>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li class="mb-2">{{ object.description }}</li>

                    </ul>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load media_tags %}
{% block content%}
{% include 'catalog/includes/inc_menu.html' with objects=objects %}
<div class="container justify-content-center">
    <div class="row text-center">
        {% for product in object_list %}
        <div class="col-12 mh-45">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
<!--                    <h4 class="my-0 font-weight-normal">{{ product.category.name }}</h4>-->
                </div>
                <div class="card-body">

                        <h2 class="card-title pricing-card-title">{{ product.name }}</h2>
                        <img src="{{ product.photo|mymedia }}" alt="{{ product.name }}">
                        <ul class="list-unstyled mt-3 mb-4 text-center m-3">
                            <li class="mb-4">{{ product.description }}</li>
                            <li class="text-center fw-bold fs-2">{{ product.price }} руб.</li>
                            <li class="text-start">Дата создания {{ product.created_at }}</li>
                            <li class="text-start">Дата изменения {{ product.updated_at }}</li>

                        </ul>
                        <button type="button" class="form-control btn btn-lg btn-block btn-outline-primary">Купить</button>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load media_tags %}
{% block content%}
{% include 'catalog/includes/inc_menu.html' %}
<div class="container justify-content-center">
    <div class="row text-center">

        <div class="col-12 mh-45">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
<!--                    <h4 class="my-0 font-weight-normal">{{ product.category.name }}</h4>-->
                </div>
                <div class="card-body">

                        <h2 class="card-title pricing-card-title">{{ object.name }}</h2>
                        <img src="{{ product.photo|mymedia }}" alt="{{ product.name }}">
                        <ul class="list-unstyled mt-3 mb-4 text-center m-3">
                            <li class="mb-4">{{ object.description }}</li>
                            <li class="text-center fw-bold fs-2">{{ object.price }} руб.</li>
                            <li class="text-start">Дата создания {{ object.created_at }}</li>
                            <li class="text-start">Дата изменения {{ object.updated_at }}</li>
                        </ul>
                        <button type="button" class="form-control btn btn-lg btn-block btn-outline-primary mb-3">Купить</button>
                        <a href="{% url 'catalog:product_delete' object.pk %}" class="form-control btn btn-lg btn-block btn-outline-primary">Удалить</a>

                </div>
            </div>
        </div>

    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% include 'catalog/includes/inc_menu.html' with objects=objects %}

<div class="container">
    <a href="{% url 'catalog:product_create' %}" class="btn btn-outline-primary mb-2">Добавить продукт</a>
    <div class="row text-center">
        {% for object in products %}
        <div class="col-4 mh-45">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.category.name }}</h4>
                </div>
                <div class="card-body">

                    <h3 class="card-title pricing-card-title">{{ object.name | truncatechars:'40' }}</h3>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li class="mb-2">{{ object.description | truncatechars:'100' }}</li>
                        <li class="text-center fw-bold mb-3">{{ object.price }} руб.</li>
                        <li>Активная версия: <strong>{{ object.active_version }}</strong></li>
                        {% if object.users.email %}
                        <li>Владелец: <strong>{{ object.users.email }}</strong></li>
                        {% else %}
                        <li>Владелец: <strong>не указан</strong></li>
                        {% endif %}
                    </ul>
                    <a href="{% url 'catalog:product_detail' object.pk %}" type="button"
                       class="form-control btn btn-lg btn-block btn-outline-primary mb-3">Купить</a>
                    {% if user.is_superuser %}
                        <a href="{% url 'catalog:product_update' object.pk %}" type="button"
                                class="form-control btn btn-lg btn-block btn-outline-primary ">Изменить</a>
                    {% else %}
                        {% if user.is_staff %}
                            {% if perms.catalog.set_is_published and perms.catalog.change_discription and perms.catalog.change_category %}
                                <a href="{% url 'catalog:product_update' object.pk %}" type="button"
                                class="form-control btn btn-lg btn-block btn-outline-primary ">Изменить</a>
                            {% endif %}
                        {% endif %}
                        {% if user.is_active %}

                                    {% if user.email == object.users.email %}

                                        <a href="{% url 'catalog:product_update' object.pk %}" type="button"
                                        class="form-control btn btn-lg btn-block btn-outline-primary ">Изменить</a>
                                    {% endif %}


                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}